name: qiga-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.5
  - numpy=2.0.1
  - scipy=1.14.1
  - python-levenshtein=0.25.1
  - matplotlib=3.9.2
  - pylatexenc=2.10
  - qiskit=1.2.1
  - ipython=8.27.0
  - jupyter=1.1.1
  - pip=24.2
  - pip:
      - qiskit==1.2.1
      - qiskit-aer==0.13.3